name: Matrix Strategy 2

on:
  push:
  workflow_dispatch:

jobs:
  deploy-all-OS:
    strategy:
      matrix:
        os: [ "${{ vars.OS_A1 }}", "${{ vars.OS_A2 }}", "${{ vars.OS_B1 }}", "${{ vars.OS_B2 }}", "${{ vars.OS_C1 }}", "${{ vars.OS_C2 }}" ]
        image: [ "${{ vars.IMG01 }}", "${{ vars.IMG02 }}" ]
        exclude:
          - os: "${{ vars.OS_C1 }}"
            image: "${{ vars.IMG01 }}"
          - os: "${{ vars.OS_C1 }}"
            image: "${{ vars.IMG02 }}"
          - os: "${{ vars.OS_C2 }}"
            image: "${{ vars.IMG01 }}"
          - os: "${{ vars.OS_C2 }}"
            image: "${{ vars.IMG02 }}"
          - os: "${{ vars.OS_B1 }}"
            image: "${{ vars.IMG02 }}"
          - os: "${{ vars.OS_B2 }}"
            image: "${{ vars.IMG02 }}"
        include:
          - os: "${{ vars.OS_A1 }}"
            image: "${{ vars.IMG03 }}"
          - os: "${{ vars.OS_A2 }}"
            image: "${{ vars.IMG03 }}"
          
    runs-on: ${{ matrix.os }}
    steps:
      - name: Display Docker Details
        run: docker info
      
      - name: Run image on ${{ matrix.os }}
        run: docker run ${{ matrix.image }}